name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true

